version: '3'

services:
  bookstore-db:
    container_name: bookstore-db
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bookstore
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
    db-data:
